# config/routes.yaml
index:
    path: /ZelFramework/Kernel/
    namespace: ZelFramework\Kernel\Tests\Controller
admin:
    path: /ZelFramework/Kernel/admin/
    namespace: ZelFramework\Kernel\Tests\Controller\Admin

default_uri: /ZelFramework/Kernel/